### ISSUE TITLE
Unintuitive error message when commands are used

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#177]
Take the example from https://microservice.guide/examples/http/pubsub/#handling-event-subscription.

It will fail with:

```
> omg validate
1 error found:
  1. root should NOT have additional properties
```

Reduced:

```yaml
version: 1
commands:
  publish:
    help: Publish an event to your service
    http:
      port: 5000
      method: post
      contentType: application/json
      path: /publish
```

I presume this is because commands was renamed into actions, but the error message should be a lot better.
