### ISSUE TITLE
validation: undefined has an issue. Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#178]
```
> omg validate
1 error found:
  1. undefined has an issue. Cannot read property 'subscribe' of undefined
```

```yaml
actions:
  listen:
    events:
      help: Subscribe to events
      heartbeat:
        help: Subscribe to heartbeat events
        http:
          port: 8080
          subscribe:
            path: /events
            method: post
            contentType: application/json
        arguments:
          eventName:
            type: string
            in: requestBody
            required: true
```

This is an example from: https://microservice.guide/schema/actions/#overview

What happened here: `help` is declared as an item of `events` and thus it tries to be parsed as an event which fails. However, the error message needs to a lot more descriptive.
