### ISSUE TITLE
'uuid4' invalid action name

### ISSUE THREAD

**Issue by kenneth-reitz** [microservices/omg#192]
the following yaml:

```yaml
actions:
  gen_uuid4:
    arguments:
      prefix:
        in: query
        required: true
        type: string
    help: Generates a UUID, with a given prefix.
    http:
      method: get
      path: /uuid4
      port: 8080
    output:
      type: string
lifecycle:
  startup:
    command:
    - python3
    - /app/service.py
omg: 1
```

Renders the following error:
```
 1. root.actions should NOT have additional properties
```

changing it to `uuid` fixes it.
