### ISSUE TITLE
Health Checks

### ISSUE THREAD

**Issue by Arinono** [microservices/omg#203]
# Health Checks

A service **SHOULD** provide health checks to ensure that the Platform knows of it's current state.
Services are consistently down will be terminated and restarted.

**Sample**
```yaml
health:
  interval: 30s
  timeout: 30s
  retries: 3
  command: ["curl", "-f", "http://localhost:8080"]
```

```html
<json-table>
<p>
{
    "interval": "How often to execute the health check `command`. This defaults to 30s",
    "timeout": "The timeout to wait for before the assuming that the command `command` failed. This defaults to 30s.",
    "retries": "The number of occurrences for the command `command` to fail continuously before the service is terminated. This defaults to 3",
    "command": {
        "desc": "The command to execute for checking the health of the service",
        "required": true
    }
}
</p>
</json-table>
```

**Comment by Arinono** [comment]
Will change schema to match Docker API (https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate)

```yaml
health:
  command: 'curl --fail http://localhost:5000/ || exit 1'
  interval: 500ms
  timeout: 1s
  retries: 3
```

**Comment by wilzbach** [comment]
Shouldn't we provide a specific endpoint instead of using curl to be more in line with OMG?

Also, I presume we could default to a reasonable default selection of parameters. In other words we should do health checks for all services and if they don't have any defined, we should use sth. akin to the command that you suggested?

**Comment by Arinono** [comment]
I was thinking about your idea to change the `command` to `endpoint` and juste let the user to provide the URL where the service exposes its health state.
The issue with this approach is that the docker image might not have `curl` packaged inside :/

**Comment by Arinono** [comment]
Right now the schema needs an `endpoint` instead of a `command`. This endpoint is an URL where the service can expose its health status (HTTP 200 == 'healthy').
This removes complexity for the developper. But, if the developper needs a more complex way of sending its microservice health status, he can still use `HEALTHCHECK` directly inside the Dockerfile of the service, and skip the `health` setup in the `microservice.yml`

```yaml
health:
  endpoint: 'http://localhost:5000/roadster'
  interval: 500ms
  timeout: 1s
  retries: 4
```

**Comment by chrisstpierre** [comment]
I'm going to argue for keeping it as `command`.

• For my microservice my release tool builds a command for performing health-checks, so I want to use that instead of curl. With only exposing an endpoint in the yml, we still cannot implement the `HEALTHCHECK` instruction in the docker file without adding curl anyways, right?
• It's a best practice to [not use curl](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/) actually.
• The entrypoint is defined in our YML, so its unintuitive that I would put a healthcheck command in the dockerfile if I do not wish to use an endpoint. I would expect healthcheck & lifecycle definitions to be used by the container
• This should be protocol agnostic unless a protocol is specified

**Comment by Arinono** [comment]
Consensus is:

OMG-cli will handle the timeout, intervals and stuff itself.

```yaml
health:
  http:
    path: '/health'
    port: 5000
```
